export let books = [
    {
        id: 1,
        name: 'Гарри Поттер',
        author: 'Джоанна Роулинг',
        price: 10,
        currency: "usd",
        language: "russian",
        stock: "stock",
    },
    {
        id: 2,
        name: 'Мертвые души',
        author: 'Николай Васильевич Гоголь',
        price: 5,
        currency: "usd",
        language: "russian",
        stock: "stock",
    },
    {
        id: 3,
        name: 'Мартин Иден',
        author: 'Джек Лондон',
        price: 8,
        currency: "usd",
        language: "russian",
        stock: "stock",
    },
    {
        id: 4,
        name: 'Белый клык',
        author: 'Джек Лондон',
        price: 12,
        currency: "usd",
        language: "russian",
        stock: "out of stock",
    },
    {
        id: 5,
        name: 'МЫ',
        author: 'Евгений Иванович Замятин',
        price: 9,
        currency: "usd",
        language: "russian",
        stock: "out of stock",
    },
    {
        id: 6,
        name: 'Гений',
        author: 'Теодор Драйзер',
        price: 13,
        currency: "usd",
        language: "russian",
        stock: "stock",
    },
    {
        id: 7,
        name: 'Шинель',
        author: 'Николай Васильевич Гоголь',
        price: 18,
        currency: "usd",
        language: "russian",
        stock: "out of stock",
    },
    {
        id: 8,
        name: 'Милый друг',
        author: 'Ги Де Мопассан',
        price: 15,
        currency: "usd",
        language: "russian",
        stock: "stock",
    },
    {
        id: 9,
        name: 'Американская Трагедия',
        author: 'Теодор Драйзер',
        price: 70,
        currency: "usd",
        language: "russian",
        stock: "out of stock",
    },
    {
        id: 10,
        name: "You don't know JS",
        author: 'Kyle Simpson',
        price: 19,
        currency: "usd",
        language: "english",
        stock: "out of stock",
    },
    {
        id: 11,
        name: 'CSS3',
        author: 'Andy Harris',
        price: 14,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 12,
        name: 'React Quickly',
        author: 'Azat Mardan',
        price: 100,
        currency: "usd",
        language: "english",
        stock: "out of stock",
    },
    {
        id: 13,
        name: 'Капитанская дочь',
        author: 'Александр Пушкин',
        price: 30,
        currency: "usd",
        language: "russian",
        stock: "stock",
    },
    {
        id: 14,
        name: 'Великий Гэтсби',
        author: 'Скотт Фицджеральд',
        price: 20,
        currency: "usd",
        language: "russian",
        stock: "stock",
    },
    {
        id: 15,
        name: 'Повелитель мух',
        author: 'Уильям Голдинг',
        price: 10,
        currency: "usd",
        language: "russian",
        stock: "stock",
    },
    {
        id: 16,
        name: 'Морской волк',
        author: 'Джек Лондон',
        price: 10,
        currency: "usd",
        language: "russian",
        stock: "stock",
    },
    {
        id: 17,
        name: "Логика",
        author: "Гегель Георг Вильгельм Фридрих",
        price: 230,
        currency: "tjs",
        language: "russian",
        stock: "stock",
    },
    {
        id: 18,
        name: "1984",
        author: "Джордж Оруэлл",
        price: 170,
        currency: "tjs",
        language: "russian",
        stock: "stock",
    },
    {
        id: 19,
        name: "Book 19",
        author: "Author",
        price: 12,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 20,
        name: "Book 20",
        author: "Author",
        price: 19,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 21,
        name: "Book 21",
        author: "Author",
        price: 25,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 22,
        name: "Book 22",
        author: "Author",
        price: 55,
        currency: "usd",
        language: "english",
        stock: "out of stock",
    },
    {
        id: 23,
        name: "Book 23",
        author: "Author",
        price: 2,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 24,
        name: "Book 24",
        author: "Author",
        price: 300,
        currency: "tjs",
        language: "english",
        stock: "stock",
    },
    {
        id: 25,
        name: "Book 25",
        author: "Author",
        price: 520,
        currency: "tjs",
        language: "english",
        stock: "out of stock",
    },
    {
        id: 26,
        name: "Book 26",
        author: "Author",
        price: 32,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 27,
        name: "Book 27",
        author: "Author",
        price: 88,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 28,
        name: "Book 28",
        author: "Author",
        price: 61,
        currency: "usd",
        language: "english",
        stock: "out of stock",
    },
    {
        id: 29,
        name: "Book 29",
        author: "Author",
        price: 92,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 30,
        name: "Книга 30",
        author: "Автор",
        price: 64,
        currency: "usd",
        language: "russian",
        stock: "stock",
    },
    {
        id: 31,
        name: "Книга 31",
        author: "Автор",
        price: 120,
        currency: "usd",
        language: "russian",
        stock: "stock",
    },
    {
        id: 32,
        name: "Книга 32",
        author: "Автор",
        price: 70,
        currency: "usd",
        language: "russian",
        stock: "out of stock",
    },
    {
        id: 33,
        name: "Книга 33",
        author: "Автор",
        price: 1500,
        currency: "tjs",
        language: "russian",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
    {
        id: 34,
        name: "Book 34",
        author: "Author",
        price: 23,
        currency: "usd",
        language: "english",
        stock: "stock",
    },
];

export let usd = 10.20;